//
//  PTConstants.swift
//  PhilipTour
//
//  Created by NHN on 2021/01/16.
//

let PT_SUCCESS = 0
let PT_ERROR_AUTH_NOT_EXIST_USER = 100
let PT_ERROR_AUTH_INCORRECT_PASSWORD = 101
let PT_ERROR_AUTH_INVALID_PARAMETER = 102
let PT_ERROR_AUTH_DUPLICATE_USERID = 103
let PT_ERROR_AUTH_PASSWORD_MISSMATCH = 104
let PT_ERROR_AUTH_SERVER_ERROR = 109
